# Pre-commit hooks configuration
# Install: pip install pre-commit
# Setup: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: ['--line-length=120']
        exclude: '^(docs|archive|\.git)'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '120']
        exclude: '^(docs|archive|\.git)'

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=E203,W503']
        exclude: '^(docs|archive|\.git)'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        args: ['--ignore-missing-imports', '--no-strict-optional']
        files: '^(core|plugins|web)/'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: '^orchestrator/schemas/'
      - id: check-json
        exclude: '^config/dashboard_.*\.json$'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-docstring-first
        files: '\.py$'
      - id: debug-statements
      - id: name-tests-test
        files: '^tests/'
        exclude: '^tests/(smoke|integration)/'

  - repo: local
    hooks:
      - id: check-requirements
        name: Check requirements.txt
        entry: python -c "import pathlib; req = pathlib.Path('requirements.txt'); assert req.exists() and req.stat().st_size > 0"
        language: system
        pass_filenames: false
        always_run: true
      
      - id: no-russian-in-code
        name: No Russian in Python code
        entry: '[\u0400-\u04FF]'
        language: pygrep
        files: '\.py$'
        exclude: '^(docs|tests|config)/'
      
      - id: validate-json-schemas
        name: Validate JSON schemas
        entry: python -m jsonschema
        language: system
        files: '^orchestrator/schemas/.*\.json$'
        pass_filenames: false
